
BOARD_SIZE = 9
board_size_sqr = BOARD_SIZE * BOARD_SIZE
possible_moves_total = BOARD_SIZE * BOARD_SIZE * 2 + 1

MAX_KOMI = 15
MEAN_KOMI = 7.5
FLAT_RANDOM_KOMI_CHANCE = 0.03
KOMI_STD_DEV = 1

EMPTY = 0
BLACK = 1
WHITE = 2


STATES_TO_NN = 32
IN_CHANNELS = STATES_TO_NN + 1
symbols = {
    BLACK: '⚫',
    WHITE: '🔴',
    EMPTY + 10 : '❎',
    EMPTY + 100 : '🟩',
    EMPTY : '⬜',
}
DEEP_DEPTH = 400
SHALLOW_DEPTH = 50
CONV_CHANNELS = 64
FEATURES = 64
NUM_RES_BLOCKS = 7

ALLOW_EARLY_RESIGN = True
UNTIL_THE_END_CHANCE = 1 if not ALLOW_EARLY_RESIGN else 0.1
CONCEDE_AT = -1.0
MIN_TURNS = 40


DEEP_SEARCH_CHANCE = 0.25

REPLAY_BUFFER_LENGTH = 500000
MAX_MOVES_PER_GAME = 150
DRAW_AT_MAX_TURNS = False

NN_HISTORY = 20 + 2 * MAX_MOVES_PER_GAME
MAX_HISTORY = 20 + 2 * MAX_MOVES_PER_GAME

INFERENCE_SERVICES_COUNT = 4
PROCESSES_PER_WORKER = 48
WORKER_COUNT = 2

SAMPLES_PER_TRAINING = 20000
TRAINING_STEPS = 300
BATCH_SIZE = 256
LEARNING_RATE = 1e-3

NN_BATCH_SIZE = int(7.0 / 8.0 * PROCESSES_PER_WORKER * WORKER_COUNT / INFERENCE_SERVICES_COUNT)
INFERENCE_TIMEOUT_MS = 5

TEMP_DECAY_TURN = 40
TEMP_DECAY_COEFF = 0.95
SMALL_TEMP = 0.3 #Меньше будет счиаться нулевой

C_PUCT = 2.7


LONG_GAME_VALUE = -0.3

PUNISH_LONG_GAME = False
EXPECTED_MAX_LENGTH = board_size_sqr - 2 * BOARD_SIZE
GAME_LENGTH_PENALTY_WEIGHT = 0.3

ENABLE_KOMI_BALANCING = False