BOARD_SIZE = 7
board_size_sqr = BOARD_SIZE * BOARD_SIZE
possible_moves_total = BOARD_SIZE * BOARD_SIZE * 2 + 1

MAX_KOMI = 15
MEAN_KOMI = 2.5
FLAT_RANDOM_KOMI_CHANCE = 0.03
KOMI_STD_DEV = 1

EMPTY = 0
BLACK = 1
WHITE = 2
NN_HISTORY = 100
MAX_HISTORY = 1000
STATES_TO_NN = 32
IN_CHANNELS = STATES_TO_NN + 1
symbols = {
    BLACK: '⚫',
    WHITE: '🔴',
    EMPTY + 10 : '❎',
    EMPTY + 100 : '🟩',
    EMPTY : '⬜',
}
DEEP_DEPTH = 400
SHALLOW_DEPTH = 400
CONV_CHANNELS = 64
FEATURES = 64
NUM_RES_BLOCKS = 7
UNTIL_THE_END_CHANCE = 0.1
CONCEDE_AT = 0.9
DEEP_SEARCH_CHANCE = 0.25
